// This file is auto-generated by @hey-api/openapi-ts

export type BodyUploadFilesChatUploadPost = {
    conversation_id: string;
    files: Array<Blob | File>;
};

export type ChatRequest = {
    conversation_id: string;
    content: string;
};

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

export type SheetCreateRequest = {
    title: string;
    headers: Array<string>;
    conversation_id: string;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type ChatStreamChatStreamPostData = {
    body: ChatRequest;
    path?: never;
    query?: never;
    url: '/chat/stream';
};

export type ChatStreamChatStreamPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChatStreamChatStreamPostError = ChatStreamChatStreamPostErrors[keyof ChatStreamChatStreamPostErrors];

export type ChatStreamChatStreamPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UploadFilesChatUploadPostData = {
    body: BodyUploadFilesChatUploadPost;
    path?: never;
    query?: never;
    url: '/chat/upload';
};

export type UploadFilesChatUploadPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadFilesChatUploadPostError = UploadFilesChatUploadPostErrors[keyof UploadFilesChatUploadPostErrors];

export type UploadFilesChatUploadPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ChatStreamWithFilesChatStreamWithFilesPostData = {
    body: ChatRequest;
    path?: never;
    query?: never;
    url: '/chat/stream-with-files';
};

export type ChatStreamWithFilesChatStreamWithFilesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChatStreamWithFilesChatStreamWithFilesPostError = ChatStreamWithFilesChatStreamWithFilesPostErrors[keyof ChatStreamWithFilesChatStreamWithFilesPostErrors];

export type ChatStreamWithFilesChatStreamWithFilesPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreateSheetSheetsCreatePostData = {
    body: SheetCreateRequest;
    path?: never;
    query?: never;
    url: '/sheets/create';
};

export type CreateSheetSheetsCreatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateSheetSheetsCreatePostError = CreateSheetSheetsCreatePostErrors[keyof CreateSheetSheetsCreatePostErrors];

export type CreateSheetSheetsCreatePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};